"""empty message

Revision ID: 1fb0d4074a22
Revises: 65fc4f850263
Create Date: 2022-12-15 14:16:33.148392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb0d4074a22'
down_revision = '65fc4f850263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('private_file', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'private_file')
    # ### end Alembic commands ###
