"""otp

Revision ID: 56feaa13042c
Revises: ade7ec38e619
Create Date: 2023-05-02 15:57:21.944812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56feaa13042c'
down_revision = 'ade7ec38e619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp')
    # ### end Alembic commands ###
