"""passive delete

Revision ID: 57c8e4adf636
Revises: 56feaa13042c
Create Date: 2023-05-03 06:28:15.938158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c8e4adf636'
down_revision = '56feaa13042c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('comment_file_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('like_comment_id_fkey', 'like', type_='foreignkey')
    op.drop_column('like', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('like_comment_id_fkey', 'like', 'comment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_file_id_fkey', 'comment', 'file', ['file_id'], ['id'])
    op.alter_column('comment', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
