"""empty message

Revision ID: 614cb7f4c630
Revises: ce0b400706d8
Create Date: 2022-09-18 09:23:54.748444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614cb7f4c630'
down_revision = 'ce0b400706d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###
