"""empty message

Revision ID: 76b3dde20e08
Revises: 99d2b8159a03
Create Date: 2022-12-17 19:12:25.550486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b3dde20e08'
down_revision = '99d2b8159a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_pic',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_pic',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
