"""empty message

Revision ID: 99d2b8159a03
Revises: 1fb0d4074a22
Create Date: 2022-12-17 13:59:49.715234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d2b8159a03'
down_revision = '1fb0d4074a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'like', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_column('like', 'comment_id')
    # ### end Alembic commands ###
