"""empty message

Revision ID: a602e80f6f21
Revises: 42d8bf54e8ec
Create Date: 2022-11-30 23:44:27.863583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a602e80f6f21'
down_revision = '42d8bf54e8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('profile_pic', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
