"""empty message

Revision ID: c5ea4dadcef3
Revises: c73f4144a28b
Create Date: 2022-09-19 15:08:46.106211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ea4dadcef3'
down_revision = 'c73f4144a28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('upload', sa.Column('description', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'upload', ['filename'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload', type_='unique')
    op.drop_column('upload', 'description')
    op.drop_column('upload', 'title')
    # ### end Alembic commands ###
